# Generated by Django 5.2.4 on 2025-09-18 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_moduels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address2',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس دوم'),
        ),
        migrations.AddField(
            model_name='user',
            name='address3',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس سوم'),
        ),
        migrations.AddField(
            model_name='user',
            name='address_org',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس اصلی'),
        ),
    ]
