# Generated by Django 5.2.4 on 2025-09-18 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0001_initial'),
        ('product_app', '0004_productimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مبلغ نهایی')),
                ('payment_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ پرداخت')),
                ('original_cart', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='order_app.order', verbose_name='سبد خرید اصلی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سفارش نهایی',
                'verbose_name_plural': 'سفارشات نهایی',
            },
        ),
        migrations.CreateModel(
            name='FinalOrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_at_purchase', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت در زمان خرید')),
                ('count', models.IntegerField(verbose_name='تعداد')),
                ('final_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_order_details', to='order_app.finalorder', verbose_name='سفارش نهایی')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product_app.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'جزئیات سفارش نهایی',
                'verbose_name_plural': 'جزئیات سفارشات نهایی',
            },
        ),
    ]
