# Generated by Django 5.2.4 on 2025-09-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_title', models.CharField(max_length=100, verbose_name='عنوان پیام')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('contact_fullname', models.CharField(max_length=50, verbose_name='نام و نام خانوادگی')),
                ('contact_phone_number', models.CharField(max_length=12, verbose_name='شماره تماس')),
                ('contact_message', models.TextField(verbose_name='متن پیام مخاطب')),
                ('contact_admin_message', models.TextField(verbose_name='پیام ادمین')),
                ('contact_is_read_admin', models.BooleanField(default=False, verbose_name='خوانده شده / خوانده نشده')),
                ('contact_created_data', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت پیام')),
            ],
        ),
    ]
